"use client";
import { useEffect, useState } from "react";
import { LogoMark } from "./Logo";
export function Report({ caseId, onClose }: { caseId: string | null; onClose: () => void }) {
  const [data, setData] = useState<any>(null);
  useEffect(() => { if (caseId) fetch(`${(typeof window!=="undefined"&&(window as any).__VERITAS_API__)||"http://localhost:8787"}/api/case/${caseId}/report`).then(r => r.json()).then(setData).catch(() => {}); }, [caseId]);
  return (
    <div className="fixed inset-0 z-50 bg-black/30 flex justify-center overflow-y-auto py-10" onClick={onClose}>
      <div className="bg-[#F6F1E4] w-[760px] max-w-[92vw] rounded-card p-12 shadow-2xl h-fit" onClick={e => e.stopPropagation()}>
        <div className="flex items-center gap-3 mb-8"><LogoMark size={40} /><div><div className="serif text-2xl font-medium">Fraud Examination Report</div><div className="text-ink-60 text-sm">Meridian Traders Pvt Ltd · FY 2025-26</div></div></div>
        {!data ? <div className="sk h-40 rounded-card" /> : (
          <div className="space-y-6">
            <Section n="1" title="Scope"><p>Complete examination of the general ledger, {data.findings?.length ? "" : ""}all invoices, bank statements, vendor master, and employee records for the fiscal year.</p></Section>
            <Section n="2" title="Findings">
              {data.findings?.map((f: any) => (
                <div key={f.id} className="mb-4 border-l-2 border-crimson pl-4">
                  <div className="font-semibold">{f.id} · {f.class}</div>
                  <p className="mt-1">{f.statement}</p>
                  <div className="mt-2 space-y-1">{f.evidence?.map((e: any, i: number) => <div key={i} className="text-[13px] text-ink-60">• {e.claim} <span className="mono text-crimson">[{(e.doc_ids ?? [e.verified_by]).join(", ")}]</span></div>)}</div>
                </div>
              ))}
            </Section>
            <Section n="3" title="Cleared items">{data.cleared?.map((h: any) => <p key={h.hypId} className="mb-2 text-ink-60">• {h.statement} <span className="text-green">— cleared</span></p>)}</Section>
            <Section n="4" title="Recommendations">{data.findings?.[0]?.recommendedActions?.map((a: string, i: number) => <p key={i}>• {a}</p>)}</Section>
            <div className="text-xs text-ink-60 pt-4 border-t border-ink-30">Generated by VERITAS · every claim cited · elapsed {data.elapsedS}s · compute cost ${data.usd}</div>
          </div>
        )}
        <button onClick={onClose} className="mt-8 text-sm text-ink-60 hover:text-ink">← Back to console</button>
      </div>
    </div>
  );
}
function Section({ n, title, children }: any) { return <div><h3 className="serif text-xl font-medium mb-2">{n}. {title}</h3><div className="text-[15px] leading-relaxed">{children}</div></div>; }
